export const incomeTransactions = [
  {
    id: 'INC-001',
    date: '2024-03-15',
    customer: 'Rahul Sharma',
    bookingId: 'BK-1001',
    source: 'Advance Payment',
    paymentMode: 'Bank Transfer',
    amount: 150000,
    account: 'Bank Account',
    status: 'Completed',
  },
  {
    id: 'INC-002',
    date: '2024-03-14',
    customer: 'Amit Verma',
    bookingId: 'BK-1002',
    source: 'Final Payment',
    paymentMode: 'Cheque',
    amount: 200000,
    account: 'Bank Account',
    status: 'Completed',
  },
  {
    id: 'INC-003',
    date: '2024-03-12',
    customer: 'Neha Gupta',
    bookingId: 'BK-1003',
    source: 'Advance Payment',
    paymentMode: 'Cash',
    amount: 50000,
    account: 'Cash Account',
    status: 'Completed',
  },
];

export const expenseTransactions = [
  {
    id: 'EXP-001',
    date: '2024-03-14',
    vendor: 'Royal Caterers',
    category: 'Catering',
    paymentMode: 'UPI',
    amount: 80000,
    account: 'Bank Account',
    status: 'Completed',
    expenseType: 'Booking',
    bookingId: 'BK-1001',
  },
  {
    id: 'EXP-002',
    date: '2024-03-13',
    vendor: 'City Power Corp',
    category: 'Electricity',
    paymentMode: 'Bank Transfer',
    amount: 45000,
    account: 'Bank Account',
    status: 'Completed',
    expenseType: 'General',
  },
  {
    id: 'EXP-003',
    date: '2024-03-10',
    vendor: 'A1 Decorators',
    category: 'Decoration',
    paymentMode: 'Cash',
    amount: 25000,
    account: 'Cash Account',
    status: 'Completed',
    expenseType: 'Booking',
    bookingId: 'BK-1002',
  },
];

export const summaryData = {
  totalIncomeToday: 150000,
  totalExpensesToday: 45000,
  netBalanceToday: 105000,
};
